modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory
logoFile="bleachmod-banner.png" #optional

license="MIT License" #mandatory

[[mods]] #mandatory
    modId="bleachmod" #mandatory
    version="1.18-1.4" #mandatory
    displayName="jdawg3636's Bleach Mod" #mandatory
    credits="\nThe Internet, for inspiring this abomination.\n" #optional
    authors="jdawg3636" #optional
    description="\nStick it to your XBOX Live haters by drinking bleach... in MINECRAFT!"